###Importar Bibliotecas

In [57]:
import pandas as pd

##Importar dados e processamento de dados

In [58]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Ciência de Dados e Inteligência Artificial/Mineração de dados/Datasets/BMR_Dataset.csv')
df.head()

   user_id   age     weight      height  gender          BMR
0     1243  27.0  73.066833  162.723887    Male  1576.878448
1     4971  28.0  77.730284  179.495414  Female  1536.656455
2     1629  57.0  85.704790  158.403052    Male  1697.694955
3     6201  47.0  67.012186  168.113746    Male  1471.524942
4     7833  36.0  79.929512  175.561126    Male  1743.147435

In [59]:
df.drop(columns=['user_id'], inplace=True)
df.head()

    age     weight      height  gender          BMR
0  27.0  73.066833  162.723887    Male  1576.878448
1  28.0  77.730284  179.495414  Female  1536.656455
2  57.0  85.704790  158.403052    Male  1697.694955
3  47.0  67.012186  168.113746    Male  1471.524942
4  36.0  79.929512  175.561126    Male  1743.147435

In [60]:
X, y = df.drop(columns=['BMR']), df['BMR']

In [61]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [62]:
X_train.select_dtypes(include='object')

      gender
6317    Male
740     Male
3781  Female
7850    Male
2963    Male
...      ...
5734  Female
5191  Female
5390    Male
860     Male
7270    Male

[7200 rows x 1 columns]

In [63]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(sparse_output=False)
X_cat = ohe.fit_transform(X_train.select_dtypes(include='object'))
X_cat_df = pd.DataFrame(X_train, columns=ohe.get_feature_names_out())
X_cat_df.head()

      gender_Female  gender_Male  gender_nan
6317            NaN          NaN         NaN
740             NaN          NaN         NaN
3781            NaN          NaN         NaN
7850            NaN          NaN         NaN
2963            NaN          NaN         NaN

In [64]:
X_train = pd.concat([X_cat_df, X.select_dtypes(include=['number'])], axis=1)
X_train.head()

      gender_Female  gender_Male  gender_nan   age      weight      height
6317            NaN          NaN         NaN  32.0   72.380435  182.735573
740             NaN          NaN         NaN  47.0   73.664635  159.290008
3781            NaN          NaN         NaN  27.0   72.861273  176.984767
7850            NaN          NaN         NaN  51.0  102.980871  147.693695
2963            NaN          NaN         NaN  27.0   55.730900  170.618041

## Normalização dos dados

In [65]:
from sklearn.preprocessing import (StandardScaler, MinMaxScaler)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_train)
X_scaled_df = pd.DataFrame(X_scaled, columns=X_train.columns)
X_scaled_df.head()

/usr/local/lib/python3.11/dist-packages/sklearn/utils/extmath.py:1101: RuntimeWarning: invalid value encountered in divide
  updated_mean = (last_sum + new_sum) / updated_sample_count
/usr/local/lib/python3.11/dist-packages/sklearn/utils/extmath.py:1106: RuntimeWarning: invalid value encountered in divide
  T = new_sum / new_sample_count
/usr/local/lib/python3.11/dist-packages/sklearn/utils/extmath.py:1126: RuntimeWarning: invalid value encountered in divide
  new_unnormalized_variance -= correction**2 / new_sample_count

   gender_Female  gender_Male  gender_nan       age    weight    height
0            NaN          NaN         NaN -0.659973  0.183298  1.296542
1            NaN          NaN         NaN  0.443994  0.268707 -1.073218
2            NaN          NaN         NaN -1.027962  0.215277  0.715280
3            NaN          NaN         NaN  0.738385  2.218463 -2.245315
4            NaN          NaN         NaN -1.027962 -0.924024  0.071763

In [66]:
X_scaled_df.shape

(9000, 6)

## Treinando o Modelo

In [67]:
import lightgbm as lgb
lgb_regressor = lgb.LGBMRegressor()
lgb_regressor.fit(X_scaled_df, y)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000441 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 559
[LightGBM] [Info] Number of data points in the train set: 9000, number of used features: 3
[LightGBM] [Info] Start training from score 1475.479479

LGBMRegressor()

In [68]:
X_train.shape

(9000, 6)